# Generated by Django 4.2.9 on 2024-01-13 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('unique_key', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('engine_oil', models.IntegerField(null=True)),
                ('gearbox_oil', models.IntegerField(null=True)),
                ('brake_fluid', models.IntegerField(null=True)),
                ('hydraulic_fluid', models.IntegerField(null=True)),
                ('hydraulic_fluid_updated_date', models.DateTimeField(null=True)),
                ('oil_filter', models.IntegerField(null=True)),
                ('fuel_filter', models.IntegerField(null=True)),
                ('air_filter', models.IntegerField(null=True)),
                ('cabin_air_filter', models.IntegerField(null=True)),
                ('cabin_air_filter_updated_date', models.DateTimeField(null=True)),
                ('timing_belt', models.IntegerField()),
                ('alternator_belt', models.IntegerField()),
                ('front_brake_pads', models.IntegerField(null=True)),
                ('rear_brake_pads', models.IntegerField(null=True)),
                ('spark_plug', models.IntegerField(null=True)),
                ('front_suspension', models.IntegerField(null=True)),
                ('cooler_gas', models.IntegerField(null=True)),
                ('clutch_plate', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_company', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('unique_key', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('car_model', models.CharField(max_length=256)),
                ('car_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminder.carcompany')),
            ],
        ),
        migrations.CreateModel(
            name='CarCustomizeSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_oil', models.IntegerField(default=6000)),
                ('brake_fluid', models.IntegerField(default=50000)),
                ('hydraulic_fluid', models.IntegerField(default=50000)),
                ('oil_filter', models.IntegerField(default=6000)),
                ('fuel_filter', models.IntegerField(default=12000)),
                ('air_filter', models.IntegerField(default=50000)),
                ('cabin_air_filter', models.IntegerField(default=50000)),
                ('timing_belt', models.IntegerField(default=60000)),
                ('alternator_belt', models.IntegerField(default=30000)),
                ('front_brake_pads', models.IntegerField(default=25000)),
                ('rear_brake_pads', models.IntegerField(default=70000)),
                ('spark_plug', models.IntegerField(default=60000)),
                ('front_suspension', models.IntegerField(default=80000)),
                ('cooler_gas_change_years', models.IntegerField(default=3)),
                ('clutch_plate', models.IntegerField(default=60000)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reminder.car')),
            ],
        ),
    ]
