# Generated by Django 4.2.9 on 2024-02-14 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Mileage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('unique_key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('engine_oil', models.IntegerField(null=True)),
                ('gearbox_oil', models.IntegerField(null=True)),
                ('brake_fluid', models.IntegerField(null=True)),
                ('hydraulic_fluid', models.IntegerField(null=True)),
                ('hydraulic_fluid_updated_date', models.DateTimeField(null=True)),
                ('oil_filter', models.IntegerField(null=True)),
                ('fuel_filter', models.IntegerField(null=True)),
                ('air_filter', models.IntegerField(null=True)),
                ('cabin_air_filter', models.IntegerField(null=True)),
                ('cabin_air_filter_updated_date', models.DateTimeField(null=True)),
                ('timing_belt', models.IntegerField(null=True)),
                ('alternator_belt', models.IntegerField(null=True)),
                ('front_brake_pads', models.IntegerField(null=True)),
                ('rear_brake_pads', models.IntegerField(null=True)),
                ('spark_plug', models.IntegerField(null=True)),
                ('front_suspension', models.IntegerField(null=True)),
                ('cooler_gas', models.IntegerField(null=True)),
                ('clutch_plate', models.IntegerField(null=True)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_mileages', to='reminder.car')),
            ],
        ),
        migrations.CreateModel(
            name='CustomFiled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('mileage_per_change', models.IntegerField(null=True)),
                ('month_per_changes', models.IntegerField(null=True)),
                ('year_per_changes', models.IntegerField(null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_custom_fileds', to='reminder.car')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('car_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminder.carcompany')),
            ],
        ),
        migrations.CreateModel(
            name='CarCustomSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_oil', models.IntegerField(default=6000)),
                ('brake_fluid', models.IntegerField(default=50000)),
                ('hydraulic_fluid', models.IntegerField(default=50000)),
                ('gearbox_oil', models.IntegerField(default=70000)),
                ('oil_filter', models.IntegerField(default=6000)),
                ('fuel_filter', models.IntegerField(default=12000)),
                ('air_filter', models.IntegerField(default=50000)),
                ('cabin_air_filter', models.IntegerField(default=50000)),
                ('timing_belt', models.IntegerField(default=60000)),
                ('alternator_belt', models.IntegerField(default=30000)),
                ('front_brake_pads', models.IntegerField(default=25000)),
                ('rear_brake_pads', models.IntegerField(default=70000)),
                ('spark_plug', models.IntegerField(default=60000)),
                ('front_suspension', models.IntegerField(default=80000)),
                ('cooler_gas_change_years', models.IntegerField(default=3)),
                ('clutch_plate', models.IntegerField(default=60000)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reminder.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_cars', to='reminder.carmodel'),
        ),
        migrations.AddField(
            model_name='car',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cars', to=settings.AUTH_USER_MODEL),
        ),
    ]
