# Generated by Django 4.2.9 on 2024-01-12 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_company', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('unique_key', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('car_model', models.CharField(max_length=256)),
                ('car_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminder.carcompany')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('unique_key', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
