# Generated by Django 4.2.9 on 2024-02-14 17:09

from django.db import migrations, models
import functools
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='unique_key',
            field=models.CharField(default=functools.partial(secrets.token_urlsafe, *(), **{'nbytes': 32}), max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='unique_key',
            field=models.CharField(default=functools.partial(secrets.token_urlsafe, *(), **{'nbytes': 32}), max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='mileage',
            name='unique_key',
            field=models.CharField(default=functools.partial(secrets.token_urlsafe, *(), **{'nbytes': 32}), max_length=70, unique=True),
        ),
    ]
