# Generated by Django 4.2.9 on 2024-02-12 17:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mileage',
            fields=[
                ('mileage', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('unique_key', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('engine_oil', models.IntegerField(null=True)),
                ('gearbox_oil', models.IntegerField(null=True)),
                ('brake_fluid', models.IntegerField(null=True)),
                ('hydraulic_fluid', models.IntegerField(null=True)),
                ('hydraulic_fluid_updated_date', models.DateTimeField(null=True)),
                ('oil_filter', models.IntegerField(null=True)),
                ('fuel_filter', models.IntegerField(null=True)),
                ('air_filter', models.IntegerField(null=True)),
                ('cabin_air_filter', models.IntegerField(null=True)),
                ('cabin_air_filter_updated_date', models.DateTimeField(null=True)),
                ('timing_belt', models.IntegerField(null=True)),
                ('alternator_belt', models.IntegerField(null=True)),
                ('front_brake_pads', models.IntegerField(null=True)),
                ('rear_brake_pads', models.IntegerField(null=True)),
                ('spark_plug', models.IntegerField(null=True)),
                ('front_suspension', models.IntegerField(null=True)),
                ('cooler_gas', models.IntegerField(null=True)),
                ('clutch_plate', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CarMileage',
        ),
        migrations.AddField(
            model_name='mileage',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_mileages', to='reminder.car'),
        ),
    ]
