# Generated by Django 4.2.9 on 2024-02-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_alter_car_unique_key_alter_carmodel_unique_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfiled',
            name='last_date_changed',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customfiled',
            name='last_mileage_changed',
            field=models.IntegerField(null=True),
        ),
    ]
