# Generated by Django 4.2.9 on 2024-02-19 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reminder", "0004_remove_customfiled_year_per_changes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mileage",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="car_mileages",
                to="reminder.car",
            ),
        ),
    ]
