# Generated by Django 4.2.9 on 2024-02-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminder", "0005_alter_mileage_car"),
    ]

    operations = [
        migrations.AddField(
            model_name="carcustomsetup",
            name="timing_belt_filter_updated_date",
            field=models.IntegerField(default=60000),
        ),
    ]
