# Generated by Django 4.2.9 on 2024-03-04 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "reminder",
            "0007_remove_carcustomsetup_timing_belt_filter_updated_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="carcustomsetup",
            name="car",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="setup",
                to="reminder.car",
            ),
        ),
    ]
