# Generated by Django 4.2.9 on 2024-03-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminder", "0008_alter_carcustomsetup_car"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carcustomsetup",
            old_name="timing_belt_filter_max_year",
            new_name="timing_belt_max_year",
        ),
        migrations.RenameField(
            model_name="mileage",
            old_name="cabin_air_filter_updated_date",
            new_name="timing_belt_last_updated_date",
        ),
        migrations.RemoveField(
            model_name="carcustomsetup",
            name="brake_fluid",
        ),
        migrations.RemoveField(
            model_name="mileage",
            name="brake_fluid",
        ),
        migrations.RemoveField(
            model_name="mileage",
            name="timing_belt_filter_updated_date",
        ),
        migrations.AlterField(
            model_name="mileage",
            name="air_filter",
            field=models.PositiveBigIntegerField(null=True, verbose_name="Air Filter"),
        ),
        migrations.AlterField(
            model_name="mileage",
            name="alternator_belt",
            field=models.PositiveBigIntegerField(
                null=True, verbose_name="Alternator Belt"
            ),
        ),
        migrations.AlterField(
            model_name="mileage",
            name="cabin_air_filter",
            field=models.PositiveBigIntegerField(
                null=True, verbose_name="Cabin Air Filter"
            ),
        ),
        migrations.AlterField(
            model_name="mileage",
            name="clutch_plate",
            field=models.PositiveBigIntegerField(
                null=True, verbose_name="Clutch Plate"
            ),
        ),
        migrations.AlterField(
            model_name="mileage",
            name="cooler_gas",
            field=models.PositiveBigIntegerField(null=True, verbose_name="Cooler Gas"),
        ),
        migrations.AlterField(
            model_name="mileage",
            name="engine_oil",
            field=models.PositiveBigIntegerField(null=True, verbose_name="Engine Oil"),
        ),
        migrations.AlterField(
            model_name="mileage",
            name="front_brake_pads",
            field=models.PositiveBigIntegerField(
                null=True, verbose_name="Front Brake Pads"
            ),
        ),
        migrations.AlterField(
            model_name="mileage",
            name="front_suspension",
            field=models.PositiveBigIntegerField(
                null=True, verbose_name="Front Suspension"
            ),
        ),
        migrations.AlterField(
            model_name="mileage",
            name="fuel_filter",
            field=models.PositiveBigIntegerField(null=True, verbose_name="Fuel Filter"),
        ),
        migrations.AlterField(
            model_name="mileage",
            name="gearbox_oil",
            field=models.PositiveBigIntegerField(null=True, verbose_name="Gearbox Oil"),
        ),
        migrations.AlterField(
            model_name="mileage",
            name="hydraulic_fluid",
            field=models.PositiveBigIntegerField(
                null=True, verbose_name="Hydraulic Fluid"
            ),
        ),
        migrations.AlterField(
            model_name="mileage",
            name="oil_filter",
            field=models.PositiveBigIntegerField(null=True, verbose_name="Oil Filter"),
        ),
        migrations.AlterField(
            model_name="mileage",
            name="rear_brake_pads",
            field=models.PositiveBigIntegerField(
                null=True, verbose_name="Rear Brake Pads"
            ),
        ),
        migrations.AlterField(
            model_name="mileage",
            name="spark_plug",
            field=models.PositiveBigIntegerField(null=True, verbose_name="Spark Plug"),
        ),
        migrations.AlterField(
            model_name="mileage",
            name="timing_belt",
            field=models.PositiveBigIntegerField(null=True, verbose_name="Timing Belt"),
        ),
    ]
