# Generated by Django 4.2.9 on 2024-03-10 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "reminder",
            "0009_rename_timing_belt_filter_max_year_carcustomsetup_timing_belt_max_year_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carcustomsetup",
            name="cooler_gas_change_years",
        ),
        migrations.RemoveField(
            model_name="mileage",
            name="cooler_gas",
        ),
    ]
