# Generated by Django 4.2.9 on 2024-06-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminder", "0010_remove_carcustomsetup_cooler_gas_change_years_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carcustomsetup",
            name="timing_belt_max_year",
            field=models.PositiveBigIntegerField(default=5),
        ),
    ]
