# Generated by Django 4.2.9 on 2024-08-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminder", "0011_alter_carcustomsetup_timing_belt_max_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customfiled",
            name="last_date_changed",
            field=models.DateField(null=True, verbose_name="Last Changed date"),
        ),
        migrations.AlterField(
            model_name="customfiled",
            name="last_mileage_changed",
            field=models.PositiveBigIntegerField(
                null=True, verbose_name="Last mileage changed"
            ),
        ),
        migrations.AlterField(
            model_name="customfiled",
            name="mileage_per_change",
            field=models.PositiveBigIntegerField(
                null=True, verbose_name="Mileage per change"
            ),
        ),
        migrations.AlterField(
            model_name="customfiled",
            name="month_per_changes",
            field=models.PositiveBigIntegerField(
                null=True, verbose_name="Interval Between Changes"
            ),
        ),
        migrations.AlterField(
            model_name="customfiled",
            name="name",
            field=models.CharField(max_length=256, verbose_name="Name"),
        ),
    ]
