# Generated by Django 4.2.9 on 2024-10-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminder", "0012_alter_customfiled_last_date_changed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customfiled",
            name="status",
            field=models.CharField(
                choices=[("SER", "Serious"), ("MED", "Medium"), ("INF", "Information")],
                default="INF",
                max_length=3,
            ),
        ),
    ]
